# Generated by Django 4.2.3 on 2023-07-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memeimage',
            name='name',
            field=models.CharField(default='Meme Images', max_length=225),
        ),
    ]
